name: sfleitartist
favicon: null
layout_spectrum: 0.3136201
typography_spectrum: 0.3189964
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#2f2e34'
    - '#426441'
    - '#7a956c'
    - '#abb18f'
    - '#54344c'
  brandStrength: 0.6875
  lightness: 0.625
  saturation: 0.3125
  rhythmicContrast: 0.75
purpose: []
