layout_spectrum: 0.3136201
color:
  saturation: 0.3614518
  brandStrength: 0.4892
  lightness: 0.734767
  rhythmicContrast: 0.9735511
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
typography_spectrum: 0.3189964
name: steven-fleit.artistwebsites.com
